version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false
linters:
  enable:
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - copyloopvar
    - govet
    - gosimple
    - gofmt
    - goconst
    - goimports
    - mnd
    - gocyclo
    - ineffassign
    - lll
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unused
    - unconvert
    - whitespace
    - wastedassign

  # don't enable:
  # - asciicheck
  # - scopelint
  # - gochecknoglobals
  # - gocognit
  # - godot
  # - godox
  # - goerr113
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - testpackage
  # - stylrcheck
  # - wsl
